---
mas_email: ""
mas_password: ""
mas_installed_app_ids: [] # Deprecated
mas_installed_apps:
  - { id: 447513724, name: "SmartConverter (2.3.0)" }
  - { id: 425264550, name: "Blackmagic Disk Speed Test (3.0)" }
  - { id: 540141595, name: "ResolutionTab (1.1)" }
  - { id: 409183694, name: "Keynote (6.6.2)" }
  - { id: 439277582, name: "iCleanMemory (1.6)" }
  - { id: 408981381, name: "iPhoto (9.6.1)" }
  - { id: 682658836, name: "GarageBand (10.1.6)" }
  - { id: 490152466, name: "iBooks Author (2.5)" }
  - { id: 407963104, name: "Pixelmator (3.6)" }
  - { id: 523620159, name: "CleanMyDrive 2 (2.1.6)" }
  - { id: 409203825, name: "Numbers (3.6.2)" }
  - { id: 497799835, name: "Xcode (8.2.1)" }
  - { id: 409201541, name: "Pages (5.6.2)" }
  - { id: 408981434, name: "iMovie (10.1.5)" }

mas_upgrade_all_apps: no
mas_signin_dialog: yes
